on:
  push:
    branches:
      - "main"

env:
  AWS_REGION: "us-east-1"
  STACK_NAME: "CdkWorkshopStack"
  PIPELINE_ROLE_ARN: "arn:aws:iam::457538672534:role/aws-sam-cli-managed-dev-pipe-PipelineExecutionRole-11DVLUHD6AJG"

jobs:
  aws_cdk:
    runs-on: ubuntu-latest
    steps:
      - name: Assume Role
        uses: youyo/awscredswrap@master
        with:
          role_arn: ${{ env.PIPELINE_ROLE_ARN }}
          duration_seconds: 3600
          role_session_name: "awscredswrap@GitHubActions"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ env.AWS_REGION }}

      - name: cdk deploy
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: "deploy"
          cdk_stack: ${{ env.STACK_NAME }}
          cdk_args: "--require-approval never"
          actions_comment: false
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ env.AWS_REGION }}
