on:
  push:
    branches:
      - "main"

env:
  AWS_REGION: "us-east-1"
  STACK_NAME: "CdkWorkshopStack"

jobs:
  echo:
  runs-on: ubuntu-latest
  steps:
    - name: "echo"
      use: docker://ubuntu:18.04
      with:
        args: ls -l .

  aws_cdk:
    runs-on: ubuntu-latest
    steps:
      - name: cdk deploy
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: "deploy"
          cdk_stack: ${{ env.STACK_NAME }}
          cdk_args: "--require-approval never"
          actions_comment: false
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ env.AWS_REGION }}
